const API_CODE_BY_SERVER = 9999;
const API_CODE_SUCCESS = 0;
const API_CODE_FAIL = 1;
const API_CODE_NOTFOUND = 2;
const API_CODE_VALIDATION_ERROR = 3;
const API_CODE_UNAUTHORIZED = 4;
const API_CODE_PERMISSION_DENIED = 5;

module.exports = {
    API_CODE_BY_SERVER,
    API_CODE_SUCCESS,
    API_CODE_FAIL,
    API_CODE_NOTFOUND,
    API_CODE_VALIDATION_ERROR,
    API_CODE_UNAUTHORIZED,
    API_CODE_PERMISSION_DENIED
};
